-- Firebase Auth to Supabase Auth Google User Migration SQL
-- Generated dynamically on 2026-06-24T10:17:48.504Z
-- Use this script in your Supabase SQL Editor to import Google-registered users safely.

BEGIN;


-- User: ict.team@pceastandrews.com (Firebase UID: 0n7WsgHk75MCVq41e7PSygV0tMJ3 -> Supabase UUID: 18a080c1-a016-5975-9735-ef5887edb906)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '18a080c1-a016-5975-9735-ef5887edb906',
  'authenticated',
  'authenticated',
  'ict.team@pceastandrews.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"112048352960006772112","name":"PCEA St Andrew''s","full_name":"PCEA St Andrew''s","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocKyA8PimXbL-YRHVjiWJtbxozszJXAFv0EUbIj9s6fDRw1jgw=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocKyA8PimXbL-YRHVjiWJtbxozszJXAFv0EUbIj9s6fDRw1jgw=s96-c","email":"ict.team@pceastandrews.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  'e169e00b-c81b-4886-98bd-f924313e1fa3',
  '18a080c1-a016-5975-9735-ef5887edb906',
  '{"sub":"112048352960006772112","email":"ict.team@pceastandrews.com","email_verified":true,"full_name":"PCEA St Andrew''s","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocKyA8PimXbL-YRHVjiWJtbxozszJXAFv0EUbIj9s6fDRw1jgw=s96-c"}'::jsonb,
  'google',
  '112048352960006772112',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: info@pceastandrews.org (Firebase UID: 1XYiPzmKA6hQHxjIWCUCl8X6bx22 -> Supabase UUID: 41adfd91-8aa2-5d9e-a2d6-dde873a9450a)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '41adfd91-8aa2-5d9e-a2d6-dde873a9450a',
  'authenticated',
  'authenticated',
  'info@pceastandrews.org',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"117300652669263222485","name":"Pcea St Andrews","full_name":"Pcea St Andrews","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocIREczEyHnYejolg2G77H_UCpr4wMAg4UZZ_-lzADqoq2YWZg=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocIREczEyHnYejolg2G77H_UCpr4wMAg4UZZ_-lzADqoq2YWZg=s96-c","email":"info@pceastandrews.org","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '81fe1f8c-5cba-4d4d-89b5-8b95b132715d',
  '41adfd91-8aa2-5d9e-a2d6-dde873a9450a',
  '{"sub":"117300652669263222485","email":"info@pceastandrews.org","email_verified":true,"full_name":"Pcea St Andrews","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocIREczEyHnYejolg2G77H_UCpr4wMAg4UZZ_-lzADqoq2YWZg=s96-c"}'::jsonb,
  'google',
  '117300652669263222485',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: nrakotoarivelo@yahoo.com (Firebase UID: 2FKOn1IFXoQHVirSYTuZRFcqLk33 -> Supabase UUID: 796116af-5b71-5917-b723-db7efd728896)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '796116af-5b71-5917-b723-db7efd728896',
  'authenticated',
  'authenticated',
  'nrakotoarivelo@yahoo.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"111814658936341644772","name":"Nivosoa Rakotoarivelo","full_name":"Nivosoa Rakotoarivelo","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocLUD7SbjJWE8b_DzifIbdxWmY7lENB8GInUkzhiuu_eMQCdyA=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocLUD7SbjJWE8b_DzifIbdxWmY7lENB8GInUkzhiuu_eMQCdyA=s96-c","email":"nrakotoarivelo@yahoo.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '25b30cd1-f2f0-45ea-bdcf-e63952814a47',
  '796116af-5b71-5917-b723-db7efd728896',
  '{"sub":"111814658936341644772","email":"nrakotoarivelo@yahoo.com","email_verified":true,"full_name":"Nivosoa Rakotoarivelo","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocLUD7SbjJWE8b_DzifIbdxWmY7lENB8GInUkzhiuu_eMQCdyA=s96-c"}'::jsonb,
  'google',
  '111814658936341644772',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: ericgicheru@gmail.com (Firebase UID: 7jnrSyYRVsYXk4KXzhtEX7nnQeE2 -> Supabase UUID: 4aa305a8-744a-5792-bfac-d329aed88a45)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '4aa305a8-744a-5792-bfac-d329aed88a45',
  'authenticated',
  'authenticated',
  'ericgicheru@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"105170770271823004682","name":"Eric Gicheru","full_name":"Eric Gicheru","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocL5cXFMQ7izbV6SS9iOpMkqXp05-cM5QktJv63DH35-iCyztgUA=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocL5cXFMQ7izbV6SS9iOpMkqXp05-cM5QktJv63DH35-iCyztgUA=s96-c","email":"ericgicheru@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '583a1a66-c711-48ed-924b-8ec0fc9e0fcc',
  '4aa305a8-744a-5792-bfac-d329aed88a45',
  '{"sub":"105170770271823004682","email":"ericgicheru@gmail.com","email_verified":true,"full_name":"Eric Gicheru","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocL5cXFMQ7izbV6SS9iOpMkqXp05-cM5QktJv63DH35-iCyztgUA=s96-c"}'::jsonb,
  'google',
  '105170770271823004682',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: hradmin@pceastandrews.org (Firebase UID: 9MhT8yaOezf2AXnJfmtS2RZlJOq1 -> Supabase UUID: 0224076d-7948-57ec-9311-2cda5d8dc066)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '0224076d-7948-57ec-9311-2cda5d8dc066',
  'authenticated',
  'authenticated',
  'hradmin@pceastandrews.org',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"102371323837932208327","name":"Stands HR","full_name":"Stands HR","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocLaRAPLehHghFuXcZVGrpGTt5ueHStPLZ7lR9_3uAWnIcWR_uI=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocLaRAPLehHghFuXcZVGrpGTt5ueHStPLZ7lR9_3uAWnIcWR_uI=s96-c","email":"hradmin@pceastandrews.org","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '553d316a-7c76-4951-aaa0-f6b14d641399',
  '0224076d-7948-57ec-9311-2cda5d8dc066',
  '{"sub":"102371323837932208327","email":"hradmin@pceastandrews.org","email_verified":true,"full_name":"Stands HR","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocLaRAPLehHghFuXcZVGrpGTt5ueHStPLZ7lR9_3uAWnIcWR_uI=s96-c"}'::jsonb,
  'google',
  '102371323837932208327',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: andereyerio16@gmail.com (Firebase UID: B6NWZ4Q4FoZJ60hO5i22dR9oLFs2 -> Supabase UUID: d5d080f6-70b0-50a8-8380-023580d2d652)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'd5d080f6-70b0-50a8-8380-023580d2d652',
  'authenticated',
  'authenticated',
  'andereyerio16@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"109266447986706687937","name":"Angela Ndereyerio","full_name":"Angela Ndereyerio","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocLHnEA1pJRSfGyZBboEIxqsGfTbZGByvsNfY9JodAh1KdddQoo=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocLHnEA1pJRSfGyZBboEIxqsGfTbZGByvsNfY9JodAh1KdddQoo=s96-c","email":"andereyerio16@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '2fb3158f-6f36-4f75-9903-36b93c61b074',
  'd5d080f6-70b0-50a8-8380-023580d2d652',
  '{"sub":"109266447986706687937","email":"andereyerio16@gmail.com","email_verified":true,"full_name":"Angela Ndereyerio","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocLHnEA1pJRSfGyZBboEIxqsGfTbZGByvsNfY9JodAh1KdddQoo=s96-c"}'::jsonb,
  'google',
  '109266447986706687937',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: mkamau@pceastandrews.org (Firebase UID: CzNBwHSjgqSKJBpDesjZPxX2ogu2 -> Supabase UUID: 154de7dd-09ac-59a2-aa7a-68d4d40f6463)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '154de7dd-09ac-59a2-aa7a-68d4d40f6463',
  'authenticated',
  'authenticated',
  'mkamau@pceastandrews.org',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"101376412189479498702","name":"Margaret W. Kamau","full_name":"Margaret W. Kamau","avatar_url":"https://lh3.googleusercontent.com/a-/ALV-UjVuo6rqFBVcGSek09TlpTCce98FnNcmQRvIM0i2AwpBJ_SXPIwrZv5pPAUOCZDbNqpKLYhkVz6ajjeu_ixuM8sBGyj63KUf2v45z2zI-LZDtBuXrEVVU_cgJjfQAnkkOve_pXk7gl8CGt1x_1uN7zARuzhMU1IirFHBntK9EX01wQS_rYPDMKbOISfcxs7cB_orw-oGZQPRc76WTDCzC893-F9Ut-UpaCVQBiJhDdrFcmk2S6WUzQhBVD1ZWVGIxFJrHJ5Ya8Ym4h6AsTj7DjwbbIQq5wqX-XON_t9F1YmQlUn7ebW4O5_NtsNYLZBbbYY87v8SLBPWz8Csh7qpcyOTadQ1_at2Tvd6pyFwfa6DqIHCPPJms-tHiiulmA5QdCNAya0Ntd63YDDee5tATdlRvVn5r1mr2jUDrk4hed8pdAvIRjB02rf0Yqj2cQF1kuqM1IgN5t6gPzBAABZSANii-zIo3XZlnxc_dR7eqZ3x5k3LYLbsdFnopwhzjZWCuoMRkRFPXUezLF1P7KKrqUGlEfr0GCDbPvZkQ9Z8IKJXGTvZ1DnMOcpmdB0My7O6RXgalk3qKrVazI-qk_q4qW8vURuHrsx8HdDu-BAFWQjoxlzddExneDuzyiXCqm3iXN9kXpAfHMYuIiwtUEUPS7fGspsNCPKw3wUySyXV2tCZce6NqxgVqveEDug8EeK2rG_moPAvIZvoM40z4lUwYG1el2_LpdAt8B3ZPFS2nlCxU2atdT474syUAyQJFUjbHZ6b-bjz3bCvjKbaZO5dPzyRrOwghtrY17Chi3KlVd0433fQjLLqYpaNTAbYl98j8gRVI9OplX4JWofB0HsyTtka3xW_eSVHWPbIhga6UjF3X5iM0Z3zvac5gRGqm8AKOv4FRLAMKS7fbszaP_fNXUGBkakZnSBjQ2kYbNY61u7Fzn8g3vLzWcCDUGKnkp92EZwS7vlTkNDJ-Fo-96PZLg8mWFVRk0hjXWrP2T1K924Y1Zjxx4llxyA17yTR78Q6KfpjUtfTO_yikJhRSavoo-NdqmERPovHhZ1KYS8Y91oPP4qfAfBwJw=s96-c","picture":"https://lh3.googleusercontent.com/a-/ALV-UjVuo6rqFBVcGSek09TlpTCce98FnNcmQRvIM0i2AwpBJ_SXPIwrZv5pPAUOCZDbNqpKLYhkVz6ajjeu_ixuM8sBGyj63KUf2v45z2zI-LZDtBuXrEVVU_cgJjfQAnkkOve_pXk7gl8CGt1x_1uN7zARuzhMU1IirFHBntK9EX01wQS_rYPDMKbOISfcxs7cB_orw-oGZQPRc76WTDCzC893-F9Ut-UpaCVQBiJhDdrFcmk2S6WUzQhBVD1ZWVGIxFJrHJ5Ya8Ym4h6AsTj7DjwbbIQq5wqX-XON_t9F1YmQlUn7ebW4O5_NtsNYLZBbbYY87v8SLBPWz8Csh7qpcyOTadQ1_at2Tvd6pyFwfa6DqIHCPPJms-tHiiulmA5QdCNAya0Ntd63YDDee5tATdlRvVn5r1mr2jUDrk4hed8pdAvIRjB02rf0Yqj2cQF1kuqM1IgN5t6gPzBAABZSANii-zIo3XZlnxc_dR7eqZ3x5k3LYLbsdFnopwhzjZWCuoMRkRFPXUezLF1P7KKrqUGlEfr0GCDbPvZkQ9Z8IKJXGTvZ1DnMOcpmdB0My7O6RXgalk3qKrVazI-qk_q4qW8vURuHrsx8HdDu-BAFWQjoxlzddExneDuzyiXCqm3iXN9kXpAfHMYuIiwtUEUPS7fGspsNCPKw3wUySyXV2tCZce6NqxgVqveEDug8EeK2rG_moPAvIZvoM40z4lUwYG1el2_LpdAt8B3ZPFS2nlCxU2atdT474syUAyQJFUjbHZ6b-bjz3bCvjKbaZO5dPzyRrOwghtrY17Chi3KlVd0433fQjLLqYpaNTAbYl98j8gRVI9OplX4JWofB0HsyTtka3xW_eSVHWPbIhga6UjF3X5iM0Z3zvac5gRGqm8AKOv4FRLAMKS7fbszaP_fNXUGBkakZnSBjQ2kYbNY61u7Fzn8g3vLzWcCDUGKnkp92EZwS7vlTkNDJ-Fo-96PZLg8mWFVRk0hjXWrP2T1K924Y1Zjxx4llxyA17yTR78Q6KfpjUtfTO_yikJhRSavoo-NdqmERPovHhZ1KYS8Y91oPP4qfAfBwJw=s96-c","email":"mkamau@pceastandrews.org","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  'a941cd06-a1b2-466c-963d-16b5562f02e2',
  '154de7dd-09ac-59a2-aa7a-68d4d40f6463',
  '{"sub":"101376412189479498702","email":"mkamau@pceastandrews.org","email_verified":true,"full_name":"Margaret W. Kamau","avatar_url":"https://lh3.googleusercontent.com/a-/ALV-UjVuo6rqFBVcGSek09TlpTCce98FnNcmQRvIM0i2AwpBJ_SXPIwrZv5pPAUOCZDbNqpKLYhkVz6ajjeu_ixuM8sBGyj63KUf2v45z2zI-LZDtBuXrEVVU_cgJjfQAnkkOve_pXk7gl8CGt1x_1uN7zARuzhMU1IirFHBntK9EX01wQS_rYPDMKbOISfcxs7cB_orw-oGZQPRc76WTDCzC893-F9Ut-UpaCVQBiJhDdrFcmk2S6WUzQhBVD1ZWVGIxFJrHJ5Ya8Ym4h6AsTj7DjwbbIQq5wqX-XON_t9F1YmQlUn7ebW4O5_NtsNYLZBbbYY87v8SLBPWz8Csh7qpcyOTadQ1_at2Tvd6pyFwfa6DqIHCPPJms-tHiiulmA5QdCNAya0Ntd63YDDee5tATdlRvVn5r1mr2jUDrk4hed8pdAvIRjB02rf0Yqj2cQF1kuqM1IgN5t6gPzBAABZSANii-zIo3XZlnxc_dR7eqZ3x5k3LYLbsdFnopwhzjZWCuoMRkRFPXUezLF1P7KKrqUGlEfr0GCDbPvZkQ9Z8IKJXGTvZ1DnMOcpmdB0My7O6RXgalk3qKrVazI-qk_q4qW8vURuHrsx8HdDu-BAFWQjoxlzddExneDuzyiXCqm3iXN9kXpAfHMYuIiwtUEUPS7fGspsNCPKw3wUySyXV2tCZce6NqxgVqveEDug8EeK2rG_moPAvIZvoM40z4lUwYG1el2_LpdAt8B3ZPFS2nlCxU2atdT474syUAyQJFUjbHZ6b-bjz3bCvjKbaZO5dPzyRrOwghtrY17Chi3KlVd0433fQjLLqYpaNTAbYl98j8gRVI9OplX4JWofB0HsyTtka3xW_eSVHWPbIhga6UjF3X5iM0Z3zvac5gRGqm8AKOv4FRLAMKS7fbszaP_fNXUGBkakZnSBjQ2kYbNY61u7Fzn8g3vLzWcCDUGKnkp92EZwS7vlTkNDJ-Fo-96PZLg8mWFVRk0hjXWrP2T1K924Y1Zjxx4llxyA17yTR78Q6KfpjUtfTO_yikJhRSavoo-NdqmERPovHhZ1KYS8Y91oPP4qfAfBwJw=s96-c"}'::jsonb,
  'google',
  '101376412189479498702',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: ndechejoyce@gmail.com (Firebase UID: DOEtlraEmSS6CjBqyxIRBqWjYLv1 -> Supabase UUID: 8194f3f2-bfc4-565c-8920-552d48dfb1cd)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '8194f3f2-bfc4-565c-8920-552d48dfb1cd',
  'authenticated',
  'authenticated',
  'ndechejoyce@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"107654779189793193672","name":"Joyce Ndeche","full_name":"Joyce Ndeche","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocJ85_aJvvcjCnY54mIP9EG913hFE0h42tJUOGxC2BGLlC1W_oA=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocJ85_aJvvcjCnY54mIP9EG913hFE0h42tJUOGxC2BGLlC1W_oA=s96-c","email":"ndechejoyce@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  'e0c13527-90ca-4b37-833c-8eaf19534f1b',
  '8194f3f2-bfc4-565c-8920-552d48dfb1cd',
  '{"sub":"107654779189793193672","email":"ndechejoyce@gmail.com","email_verified":true,"full_name":"Joyce Ndeche","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocJ85_aJvvcjCnY54mIP9EG913hFE0h42tJUOGxC2BGLlC1W_oA=s96-c"}'::jsonb,
  'google',
  '107654779189793193672',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: youthtreasurer@pceastandrews.org (Firebase UID: FXQTIF4dwBaak9g2lr1axYNMUIg2 -> Supabase UUID: 495728be-657a-51c4-a037-9a032c28b7dc)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '495728be-657a-51c4-a037-9a032c28b7dc',
  'authenticated',
  'authenticated',
  'youthtreasurer@pceastandrews.org',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"107990934172183497334","name":"Youth Treasurer","full_name":"Youth Treasurer","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocJKJzrVRWJyTK03jMULes21fOMw1SM0DNutaxqZhdJBJiZZQg=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocJKJzrVRWJyTK03jMULes21fOMw1SM0DNutaxqZhdJBJiZZQg=s96-c","email":"youthtreasurer@pceastandrews.org","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  'ad8e6282-9e01-471e-a734-11751f44a0ad',
  '495728be-657a-51c4-a037-9a032c28b7dc',
  '{"sub":"107990934172183497334","email":"youthtreasurer@pceastandrews.org","email_verified":true,"full_name":"Youth Treasurer","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocJKJzrVRWJyTK03jMULes21fOMw1SM0DNutaxqZhdJBJiZZQg=s96-c"}'::jsonb,
  'google',
  '107990934172183497334',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: kevintalam20@gmail.com (Firebase UID: Fd9mX7p6qEXq5dzEF27BbvZV99v2 -> Supabase UUID: 44bbd817-817c-5206-ae90-955a67a1982b)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '44bbd817-817c-5206-ae90-955a67a1982b',
  'authenticated',
  'authenticated',
  'kevintalam20@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"108002691602065821627","name":"Kevin Talam","full_name":"Kevin Talam","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocIJvzWKE4reEIFCUW3CkN0L-9ba8Rm6INGQQ8iflYqK9i9ZXuRO2A=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocIJvzWKE4reEIFCUW3CkN0L-9ba8Rm6INGQQ8iflYqK9i9ZXuRO2A=s96-c","email":"kevintalam20@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '99f22ee4-cf0a-4c9b-8b21-92f2790420bf',
  '44bbd817-817c-5206-ae90-955a67a1982b',
  '{"sub":"108002691602065821627","email":"kevintalam20@gmail.com","email_verified":true,"full_name":"Kevin Talam","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocIJvzWKE4reEIFCUW3CkN0L-9ba8Rm6INGQQ8iflYqK9i9ZXuRO2A=s96-c"}'::jsonb,
  'google',
  '108002691602065821627',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: mainaeriq@gmail.com (Firebase UID: JMJ2aBkwOeOp1qItgzq6DXDrNIa2 -> Supabase UUID: 4b4bf4b2-566d-5f33-9f0d-89c26917da35)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '4b4bf4b2-566d-5f33-9f0d-89c26917da35',
  'authenticated',
  'authenticated',
  'mainaeriq@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"107503276732455077467","name":"Erick Maina","full_name":"Erick Maina","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocK7bKgECG61PDn0zfkkKebhfGB00iJPq81KLHeoTToMkDv4boitDQ=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocK7bKgECG61PDn0zfkkKebhfGB00iJPq81KLHeoTToMkDv4boitDQ=s96-c","email":"mainaeriq@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '0d479b80-b32f-4410-8727-653a24dba340',
  '4b4bf4b2-566d-5f33-9f0d-89c26917da35',
  '{"sub":"107503276732455077467","email":"mainaeriq@gmail.com","email_verified":true,"full_name":"Erick Maina","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocK7bKgECG61PDn0zfkkKebhfGB00iJPq81KLHeoTToMkDv4boitDQ=s96-c"}'::jsonb,
  'google',
  '107503276732455077467',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: itskimathi@gmail.com (Firebase UID: JW88gtk5slNH5JmqGzqCXkkvn3k2 -> Supabase UUID: c2dcd167-4cde-5f4a-a4db-d447cacf6848)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'c2dcd167-4cde-5f4a-a4db-d447cacf6848',
  'authenticated',
  'authenticated',
  'itskimathi@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"111231286342199308619","name":"Victor Kimathi Murithi","full_name":"Victor Kimathi Murithi","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocIzsrWwK-bVX9v9psAaJn0ZY7aSwmXS8HDKHY5hE1XWBve3AKlL=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocIzsrWwK-bVX9v9psAaJn0ZY7aSwmXS8HDKHY5hE1XWBve3AKlL=s96-c","email":"itskimathi@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '94a79a40-93c6-4349-b5e9-95d358a2b344',
  'c2dcd167-4cde-5f4a-a4db-d447cacf6848',
  '{"sub":"111231286342199308619","email":"itskimathi@gmail.com","email_verified":true,"full_name":"Victor Kimathi Murithi","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocIzsrWwK-bVX9v9psAaJn0ZY7aSwmXS8HDKHY5hE1XWBve3AKlL=s96-c"}'::jsonb,
  'google',
  '111231286342199308619',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: geeshau.standsmedia@gmail.com (Firebase UID: K3jOPRaqQqROik29UIFxZJvneVL2 -> Supabase UUID: 6163b46d-1124-52a5-99cc-6aa08f357760)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '6163b46d-1124-52a5-99cc-6aa08f357760',
  'authenticated',
  'authenticated',
  'geeshau.standsmedia@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"108858132215359630282","name":"Alex Gichau","full_name":"Alex Gichau","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocKwWy74tCdl5IIzdUmL6xN-rHaY89LWz_sy4zXYkg6DSnH3igGL=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocKwWy74tCdl5IIzdUmL6xN-rHaY89LWz_sy4zXYkg6DSnH3igGL=s96-c","email":"geeshau.standsmedia@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '28461a19-e428-41e2-a665-5c4f8f697a68',
  '6163b46d-1124-52a5-99cc-6aa08f357760',
  '{"sub":"108858132215359630282","email":"geeshau.standsmedia@gmail.com","email_verified":true,"full_name":"Alex Gichau","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocKwWy74tCdl5IIzdUmL6xN-rHaY89LWz_sy4zXYkg6DSnH3igGL=s96-c"}'::jsonb,
  'google',
  '108858132215359630282',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: maxienigel@gmail.com (Firebase UID: PXhKUQV3DmcNweFQAdChmKvN52I3 -> Supabase UUID: 8dd05e38-358a-5272-99f2-71ab017a41e5)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '8dd05e38-358a-5272-99f2-71ab017a41e5',
  'authenticated',
  'authenticated',
  'maxienigel@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"115509344442853710529","name":"Maxie Nigel","full_name":"Maxie Nigel","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocKFrnVREc4EuOsbVnodjWu_SR5ETj_3dC6Pe6NZdiUuzjV-wO0a_Q=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocKFrnVREc4EuOsbVnodjWu_SR5ETj_3dC6Pe6NZdiUuzjV-wO0a_Q=s96-c","email":"maxienigel@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  'f95168e0-691c-4f09-90f9-5e926d891b20',
  '8dd05e38-358a-5272-99f2-71ab017a41e5',
  '{"sub":"115509344442853710529","email":"maxienigel@gmail.com","email_verified":true,"full_name":"Maxie Nigel","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocKFrnVREc4EuOsbVnodjWu_SR5ETj_3dC6Pe6NZdiUuzjV-wO0a_Q=s96-c"}'::jsonb,
  'google',
  '115509344442853710529',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: muthiru.calli@gmail.com (Firebase UID: S6qORdG41jRrCzrLbbl1dJeTGy03 -> Supabase UUID: 56fbd4fe-2c1b-53de-9c37-525053cdf9da)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '56fbd4fe-2c1b-53de-9c37-525053cdf9da',
  'authenticated',
  'authenticated',
  'muthiru.calli@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"115356448270861276020","name":"Callitos Muthiru","full_name":"Callitos Muthiru","avatar_url":"https://lh3.googleusercontent.com/a-/ALV-UjWrolNObiFQOY45gArkJ1RX2OrnaFScz0w434SH5FqC5AJs9dmG2ToVeZ1xOahGB4tBxI60UMRPA0mmSauZdkAvAgRjqapBM8WgOWH3XFCIWN_fDpDwShIJlfhPROHHEbNlEh753S0gWRz42sBGKOGpbnhsV80R0NJUfVXtYQFQ0N2f1J8mYR4OKbepYY1t97Q4D9VwTHPcAp5d16ZYFxox53ma7-wHBjUwXBRRZj1ngIBQnQs3icNQ6InN9E_I4mHgMQu2WOaUkmZIupIioZltodOzXii56YkrJyDBBLaa2GV6xMUM2-0qe7Q7YnvAQFW6g-_OgnR4a7bjI0GKiSg9BJIKmmNG2mpl5LCoY5KhPx2oSOgJJIUtUkWLruI8M6lFMC-g_pWOLOIiGA2WQQVCiNMByvGA-Vl3A3qdlFODFIBO2Biu0gAbD3isPifEAFMZ30Z8-uEpYf8bGpuJYUgSbBSFI3USS5jbFKIZsWMquh2hlHRY8BGxinXelvkFnOBAS8uiCv3UosvuwhSomNtJGQ2siuRx-L3ldYgOQSyFkWCL0ft7t-fvkzTBzD7wfJD4OhrNrCJBBe8fi-44ifmdtVuEjIGTPqVvEAdOIPrDthgQvabX-2G7Se_4rXoEQLKx0BhQ5bBeG0B3toOV4efm98xtp-9cRqgdEeC40dPnN5yhsBxU1GfOmRXq7JPDhcAsi9ShFV7zw_7RwAFNFEUmpV_c9cs0qAoVa6kJVUoSSdLwDklpnS0Z6seWyQsVY1RboTyN8r_QXVEhhguwZuB-ERi5VIwRrrH7d-HL7NHBTndrcNWSb1APlZzZumvF1JAVBmADuBWNXAqoziM8a2XUKFgRHCuIyK5BAzbYlvjdqZST_SxQM2g2bAzJsYtM_uiX5CHmNv5MeeF3o4n_2wU_tENfLwTP6pRvc3EmTphS7lPwYxk_ff1x_NI6vHI_O_eAN2Tgob9Un3Oe_NOsMHr6_mSA0L1eOZgc4huOPnLw7mYSmg1quRK6iN9vGaqflpPy5Dcg9ukqiS_sX1-yXetuxwJ4zzUhBPVkvcIqysg59-ztiVRs1wN7=s96-c","picture":"https://lh3.googleusercontent.com/a-/ALV-UjWrolNObiFQOY45gArkJ1RX2OrnaFScz0w434SH5FqC5AJs9dmG2ToVeZ1xOahGB4tBxI60UMRPA0mmSauZdkAvAgRjqapBM8WgOWH3XFCIWN_fDpDwShIJlfhPROHHEbNlEh753S0gWRz42sBGKOGpbnhsV80R0NJUfVXtYQFQ0N2f1J8mYR4OKbepYY1t97Q4D9VwTHPcAp5d16ZYFxox53ma7-wHBjUwXBRRZj1ngIBQnQs3icNQ6InN9E_I4mHgMQu2WOaUkmZIupIioZltodOzXii56YkrJyDBBLaa2GV6xMUM2-0qe7Q7YnvAQFW6g-_OgnR4a7bjI0GKiSg9BJIKmmNG2mpl5LCoY5KhPx2oSOgJJIUtUkWLruI8M6lFMC-g_pWOLOIiGA2WQQVCiNMByvGA-Vl3A3qdlFODFIBO2Biu0gAbD3isPifEAFMZ30Z8-uEpYf8bGpuJYUgSbBSFI3USS5jbFKIZsWMquh2hlHRY8BGxinXelvkFnOBAS8uiCv3UosvuwhSomNtJGQ2siuRx-L3ldYgOQSyFkWCL0ft7t-fvkzTBzD7wfJD4OhrNrCJBBe8fi-44ifmdtVuEjIGTPqVvEAdOIPrDthgQvabX-2G7Se_4rXoEQLKx0BhQ5bBeG0B3toOV4efm98xtp-9cRqgdEeC40dPnN5yhsBxU1GfOmRXq7JPDhcAsi9ShFV7zw_7RwAFNFEUmpV_c9cs0qAoVa6kJVUoSSdLwDklpnS0Z6seWyQsVY1RboTyN8r_QXVEhhguwZuB-ERi5VIwRrrH7d-HL7NHBTndrcNWSb1APlZzZumvF1JAVBmADuBWNXAqoziM8a2XUKFgRHCuIyK5BAzbYlvjdqZST_SxQM2g2bAzJsYtM_uiX5CHmNv5MeeF3o4n_2wU_tENfLwTP6pRvc3EmTphS7lPwYxk_ff1x_NI6vHI_O_eAN2Tgob9Un3Oe_NOsMHr6_mSA0L1eOZgc4huOPnLw7mYSmg1quRK6iN9vGaqflpPy5Dcg9ukqiS_sX1-yXetuxwJ4zzUhBPVkvcIqysg59-ztiVRs1wN7=s96-c","email":"muthiru.calli@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '48184f17-8e8a-4b1e-a150-945aa09a5391',
  '56fbd4fe-2c1b-53de-9c37-525053cdf9da',
  '{"sub":"115356448270861276020","email":"muthiru.calli@gmail.com","email_verified":true,"full_name":"Callitos Muthiru","avatar_url":"https://lh3.googleusercontent.com/a-/ALV-UjWrolNObiFQOY45gArkJ1RX2OrnaFScz0w434SH5FqC5AJs9dmG2ToVeZ1xOahGB4tBxI60UMRPA0mmSauZdkAvAgRjqapBM8WgOWH3XFCIWN_fDpDwShIJlfhPROHHEbNlEh753S0gWRz42sBGKOGpbnhsV80R0NJUfVXtYQFQ0N2f1J8mYR4OKbepYY1t97Q4D9VwTHPcAp5d16ZYFxox53ma7-wHBjUwXBRRZj1ngIBQnQs3icNQ6InN9E_I4mHgMQu2WOaUkmZIupIioZltodOzXii56YkrJyDBBLaa2GV6xMUM2-0qe7Q7YnvAQFW6g-_OgnR4a7bjI0GKiSg9BJIKmmNG2mpl5LCoY5KhPx2oSOgJJIUtUkWLruI8M6lFMC-g_pWOLOIiGA2WQQVCiNMByvGA-Vl3A3qdlFODFIBO2Biu0gAbD3isPifEAFMZ30Z8-uEpYf8bGpuJYUgSbBSFI3USS5jbFKIZsWMquh2hlHRY8BGxinXelvkFnOBAS8uiCv3UosvuwhSomNtJGQ2siuRx-L3ldYgOQSyFkWCL0ft7t-fvkzTBzD7wfJD4OhrNrCJBBe8fi-44ifmdtVuEjIGTPqVvEAdOIPrDthgQvabX-2G7Se_4rXoEQLKx0BhQ5bBeG0B3toOV4efm98xtp-9cRqgdEeC40dPnN5yhsBxU1GfOmRXq7JPDhcAsi9ShFV7zw_7RwAFNFEUmpV_c9cs0qAoVa6kJVUoSSdLwDklpnS0Z6seWyQsVY1RboTyN8r_QXVEhhguwZuB-ERi5VIwRrrH7d-HL7NHBTndrcNWSb1APlZzZumvF1JAVBmADuBWNXAqoziM8a2XUKFgRHCuIyK5BAzbYlvjdqZST_SxQM2g2bAzJsYtM_uiX5CHmNv5MeeF3o4n_2wU_tENfLwTP6pRvc3EmTphS7lPwYxk_ff1x_NI6vHI_O_eAN2Tgob9Un3Oe_NOsMHr6_mSA0L1eOZgc4huOPnLw7mYSmg1quRK6iN9vGaqflpPy5Dcg9ukqiS_sX1-yXetuxwJ4zzUhBPVkvcIqysg59-ztiVRs1wN7=s96-c"}'::jsonb,
  'google',
  '115356448270861276020',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: jeremykinyuah@gmail.com (Firebase UID: U4ecXJI6zebI3LKqmbuNioTrKFi2 -> Supabase UUID: b81b0689-b2dd-5543-a0e5-0300ab745c8d)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'b81b0689-b2dd-5543-a0e5-0300ab745c8d',
  'authenticated',
  'authenticated',
  'jeremykinyuah@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"104912005656561643224","name":"Jeremy K","full_name":"Jeremy K","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocIioTHKqdHmZNF1opTIHsx4VS-QYp2jWWPwXAK5DDflwhAvsjs=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocIioTHKqdHmZNF1opTIHsx4VS-QYp2jWWPwXAK5DDflwhAvsjs=s96-c","email":"jeremykinyuah@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  'ce72b89b-4788-4069-93f5-db6f84983113',
  'b81b0689-b2dd-5543-a0e5-0300ab745c8d',
  '{"sub":"104912005656561643224","email":"jeremykinyuah@gmail.com","email_verified":true,"full_name":"Jeremy K","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocIioTHKqdHmZNF1opTIHsx4VS-QYp2jWWPwXAK5DDflwhAvsjs=s96-c"}'::jsonb,
  'google',
  '104912005656561643224',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: ict.team@pceastandrews.org (Firebase UID: VlVvsrTZ3aO4VJP4H7npCaWEDHt1 -> Supabase UUID: 3b0633dd-14b2-5f9b-b270-3d45219e419a)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '3b0633dd-14b2-5f9b-b270-3d45219e419a',
  'authenticated',
  'authenticated',
  'ict.team@pceastandrews.org',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"104886389219383757052","name":"ICT Team","full_name":"ICT Team","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocKqZPQqdHVnrlBaC8ZCyEik6uaB3tz24c58okWF7K36Q7vv44c=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocKqZPQqdHVnrlBaC8ZCyEik6uaB3tz24c58okWF7K36Q7vv44c=s96-c","email":"ict.team@pceastandrews.org","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '57e173a3-3feb-41a4-bfad-5044e5f1059b',
  '3b0633dd-14b2-5f9b-b270-3d45219e419a',
  '{"sub":"104886389219383757052","email":"ict.team@pceastandrews.org","email_verified":true,"full_name":"ICT Team","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocKqZPQqdHVnrlBaC8ZCyEik6uaB3tz24c58okWF7K36Q7vv44c=s96-c"}'::jsonb,
  'google',
  '104886389219383757052',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: joel@pceastandrews.org (Firebase UID: XNKRgXweviTLxtnbASIh0UL8abI2 -> Supabase UUID: 02d4b214-c3c8-56fc-8b8b-5b610826fba5)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '02d4b214-c3c8-56fc-8b8b-5b610826fba5',
  'authenticated',
  'authenticated',
  'joel@pceastandrews.org',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"106939296884634568859","name":"Joel Mwaniki","full_name":"Joel Mwaniki","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocKe8jJOo6VxeA86PoACWrRgrd-5dzHOqBDpSHN0BCu_iFCoaw=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocKe8jJOo6VxeA86PoACWrRgrd-5dzHOqBDpSHN0BCu_iFCoaw=s96-c","email":"joel@pceastandrews.org","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  'cc08d341-858f-4a3e-9c89-7723686d8305',
  '02d4b214-c3c8-56fc-8b8b-5b610826fba5',
  '{"sub":"106939296884634568859","email":"joel@pceastandrews.org","email_verified":true,"full_name":"Joel Mwaniki","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocKe8jJOo6VxeA86PoACWrRgrd-5dzHOqBDpSHN0BCu_iFCoaw=s96-c"}'::jsonb,
  'google',
  '106939296884634568859',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: wmwangi507@gmail.com (Firebase UID: YbuvQrxxuGP3afnnMIIb97Ko4Nh2 -> Supabase UUID: 3898e902-a3d7-5da0-af59-76e7744d67da)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '3898e902-a3d7-5da0-af59-76e7744d67da',
  'authenticated',
  'authenticated',
  'wmwangi507@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"107391569066799185317","name":"Wanjiku Mwangi","full_name":"Wanjiku Mwangi","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocI429HttqZVW6BgrhS6B-Y_Rfv6FBQjbdm1xyICZ5_KwZ52XRzv=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocI429HttqZVW6BgrhS6B-Y_Rfv6FBQjbdm1xyICZ5_KwZ52XRzv=s96-c","email":"wmwangi507@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '78401b82-e033-41b5-b3dc-699621cca026',
  '3898e902-a3d7-5da0-af59-76e7744d67da',
  '{"sub":"107391569066799185317","email":"wmwangi507@gmail.com","email_verified":true,"full_name":"Wanjiku Mwangi","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocI429HttqZVW6BgrhS6B-Y_Rfv6FBQjbdm1xyICZ5_KwZ52XRzv=s96-c"}'::jsonb,
  'google',
  '107391569066799185317',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: trevomaina@gmail.com (Firebase UID: aqo8LQzhYEXDOMzB9tp5ICQ4NEu1 -> Supabase UUID: 61e8ff9e-912b-5e5e-b436-bace1db73827)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '61e8ff9e-912b-5e5e-b436-bace1db73827',
  'authenticated',
  'authenticated',
  'trevomaina@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"105556099998316899319","name":"Trevor Maina","full_name":"Trevor Maina","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocKSIJ8KL2kKa2CZra8nm2TtJezfFXgDjFfA0BvNl9gTuwYFzIRM=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocKSIJ8KL2kKa2CZra8nm2TtJezfFXgDjFfA0BvNl9gTuwYFzIRM=s96-c","email":"trevomaina@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '9d58c1b0-b1e6-40aa-980f-71586545e8fc',
  '61e8ff9e-912b-5e5e-b436-bace1db73827',
  '{"sub":"105556099998316899319","email":"trevomaina@gmail.com","email_verified":true,"full_name":"Trevor Maina","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocKSIJ8KL2kKa2CZra8nm2TtJezfFXgDjFfA0BvNl9gTuwYFzIRM=s96-c"}'::jsonb,
  'google',
  '105556099998316899319',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: insights.financials@gmail.com (Firebase UID: dYV9sjGfYeQuxJwQqUcU4IoqdLE3 -> Supabase UUID: e1531b0c-1394-52f4-b0b6-ceb166990c24)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'e1531b0c-1394-52f4-b0b6-ceb166990c24',
  'authenticated',
  'authenticated',
  'insights.financials@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"117724946486017221980","name":"Insights Financial services","full_name":"Insights Financial services","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocJyFpDzSCTvbyULWKz7dmHrderVDgGM_ayYv8VMod-Uh44VGCA=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocJyFpDzSCTvbyULWKz7dmHrderVDgGM_ayYv8VMod-Uh44VGCA=s96-c","email":"insights.financials@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '33668130-7682-4ede-875d-33f5cd0b1da4',
  'e1531b0c-1394-52f4-b0b6-ceb166990c24',
  '{"sub":"117724946486017221980","email":"insights.financials@gmail.com","email_verified":true,"full_name":"Insights Financial services","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocJyFpDzSCTvbyULWKz7dmHrderVDgGM_ayYv8VMod-Uh44VGCA=s96-c"}'::jsonb,
  'google',
  '117724946486017221980',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: sawamwangi@gmail.com (Firebase UID: gxngej8zObV36qR5RJIe4KwU7jg2 -> Supabase UUID: 4bb0bdee-2467-5958-8efb-649bd8a31471)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '4bb0bdee-2467-5958-8efb-649bd8a31471',
  'authenticated',
  'authenticated',
  'sawamwangi@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"102721531210976845462","name":"Samuel Mwangi","full_name":"Samuel Mwangi","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocLGWYdrj3iAH1aSkqbEcj27NM-cX7IYJqksiQXdtZoew2a0ng=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocLGWYdrj3iAH1aSkqbEcj27NM-cX7IYJqksiQXdtZoew2a0ng=s96-c","email":"sawamwangi@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  'cd60ae2b-b682-4df2-b53e-99fdf3afea46',
  '4bb0bdee-2467-5958-8efb-649bd8a31471',
  '{"sub":"102721531210976845462","email":"sawamwangi@gmail.com","email_verified":true,"full_name":"Samuel Mwangi","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocLGWYdrj3iAH1aSkqbEcj27NM-cX7IYJqksiQXdtZoew2a0ng=s96-c"}'::jsonb,
  'google',
  '102721531210976845462',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: annkamira892@gmail.com (Firebase UID: hD1TvpoOOlYSUZwXsfVChaHO68D3 -> Supabase UUID: 2c622c69-0310-5389-b8dc-343be89b65cc)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '2c622c69-0310-5389-b8dc-343be89b65cc',
  'authenticated',
  'authenticated',
  'annkamira892@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"102996628046027880125","name":"Ann Kamira","full_name":"Ann Kamira","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocIXbSbqgQ4stDQO20I0iGRM5IzsGaIArXOyksrgI0Qg8vLPSg=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocIXbSbqgQ4stDQO20I0iGRM5IzsGaIArXOyksrgI0Qg8vLPSg=s96-c","email":"annkamira892@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '17897e65-a69e-497f-8c32-1fab8ff8aca8',
  '2c622c69-0310-5389-b8dc-343be89b65cc',
  '{"sub":"102996628046027880125","email":"annkamira892@gmail.com","email_verified":true,"full_name":"Ann Kamira","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocIXbSbqgQ4stDQO20I0iGRM5IzsGaIArXOyksrgI0Qg8vLPSg=s96-c"}'::jsonb,
  'google',
  '102996628046027880125',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: jwthagichu@gmail.com (Firebase UID: iQtPrLrUCJPyDOwMvT2pXYZsbgp2 -> Supabase UUID: 741f0bfc-36a0-5799-a576-39045e63a003)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '741f0bfc-36a0-5799-a576-39045e63a003',
  'authenticated',
  'authenticated',
  'jwthagichu@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"105524480201772425438","name":"Jacqueline T.","full_name":"Jacqueline T.","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocIePPFz2MuPudGUGb127oTJt2lyBq45-UnOb3lcsKCPaubfuaFF5Q=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocIePPFz2MuPudGUGb127oTJt2lyBq45-UnOb3lcsKCPaubfuaFF5Q=s96-c","email":"jwthagichu@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  'c201d647-b838-4860-84b2-8cab0502f84a',
  '741f0bfc-36a0-5799-a576-39045e63a003',
  '{"sub":"105524480201772425438","email":"jwthagichu@gmail.com","email_verified":true,"full_name":"Jacqueline T.","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocIePPFz2MuPudGUGb127oTJt2lyBq45-UnOb3lcsKCPaubfuaFF5Q=s96-c"}'::jsonb,
  'google',
  '105524480201772425438',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: paulmhesh580@gmail.com (Firebase UID: rUbshUNyqjR0w1vaXTohUPxhIHx1 -> Supabase UUID: ca57deed-ca8c-55fb-8ef8-b8a44d2fe0a0)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'ca57deed-ca8c-55fb-8ef8-b8a44d2fe0a0',
  'authenticated',
  'authenticated',
  'paulmhesh580@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"104743797430480637284","name":"Paul Mwangi","full_name":"Paul Mwangi","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocJOCSmU195oWdRgqn5_niBiaMUsnS-MXzJ5Hyf8-0bkUa3oLg=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocJOCSmU195oWdRgqn5_niBiaMUsnS-MXzJ5Hyf8-0bkUa3oLg=s96-c","email":"paulmhesh580@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '6ef6f87a-2ed2-4f96-a671-d9f3d3f6c3ae',
  'ca57deed-ca8c-55fb-8ef8-b8a44d2fe0a0',
  '{"sub":"104743797430480637284","email":"paulmhesh580@gmail.com","email_verified":true,"full_name":"Paul Mwangi","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocJOCSmU195oWdRgqn5_niBiaMUsnS-MXzJ5Hyf8-0bkUa3oLg=s96-c"}'::jsonb,
  'google',
  '104743797430480637284',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: praiseriungu@gmail.com (Firebase UID: saZxYXIg0RVOZUAElxLl1xlez472 -> Supabase UUID: 72c98cd2-0153-5b73-bf9f-311304f9db0a)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '72c98cd2-0153-5b73-bf9f-311304f9db0a',
  'authenticated',
  'authenticated',
  'praiseriungu@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"115748209724732885640","name":"Praise Riungu","full_name":"Praise Riungu","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocJ3IY0mN17rIUSAQE9p2fGwwYvCt3Me05nUmpIJXSKJK0hom9I=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocJ3IY0mN17rIUSAQE9p2fGwwYvCt3Me05nUmpIJXSKJK0hom9I=s96-c","email":"praiseriungu@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '6bac2cf6-97ca-40e3-b4b9-3f59a9f9f893',
  '72c98cd2-0153-5b73-bf9f-311304f9db0a',
  '{"sub":"115748209724732885640","email":"praiseriungu@gmail.com","email_verified":true,"full_name":"Praise Riungu","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocJ3IY0mN17rIUSAQE9p2fGwwYvCt3Me05nUmpIJXSKJK0hom9I=s96-c"}'::jsonb,
  'google',
  '115748209724732885640',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: thaiyak@gmail.com (Firebase UID: tCQCWnfXTXREoQA44YHVvdhMTUB2 -> Supabase UUID: 7c186fbc-5fad-5dd3-93da-bc39778a1eba)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '7c186fbc-5fad-5dd3-93da-bc39778a1eba',
  'authenticated',
  'authenticated',
  'thaiyak@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"118379610513502094714","name":"Kimani Thaiya","full_name":"Kimani Thaiya","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocIB4pSQReublQ4nFukG62pHZquJOKcc6yzsTa9mexjiOn_l54o0=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocIB4pSQReublQ4nFukG62pHZquJOKcc6yzsTa9mexjiOn_l54o0=s96-c","email":"thaiyak@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  'f19a76b5-04b2-4cc6-874e-41c7cf5cebad',
  '7c186fbc-5fad-5dd3-93da-bc39778a1eba',
  '{"sub":"118379610513502094714","email":"thaiyak@gmail.com","email_verified":true,"full_name":"Kimani Thaiya","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocIB4pSQReublQ4nFukG62pHZquJOKcc6yzsTa9mexjiOn_l54o0=s96-c"}'::jsonb,
  'google',
  '118379610513502094714',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: warididada.standsyouth@gmail.com (Firebase UID: u03FjfHjFcNrQivTbURJI9cCub22 -> Supabase UUID: d0fc520f-3fa2-5f08-be9b-05b7777e4542)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'd0fc520f-3fa2-5f08-be9b-05b7777e4542',
  'authenticated',
  'authenticated',
  'warididada.standsyouth@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"106476345377454385054","name":"waridi dada","full_name":"waridi dada","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocI_XNxC8tLMfHd5mbc4Ayu05Io5xEdcXGSufis3n6cuT8ixkA=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocI_XNxC8tLMfHd5mbc4Ayu05Io5xEdcXGSufis3n6cuT8ixkA=s96-c","email":"warididada.standsyouth@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '8c8072e8-b246-43d6-801c-f895ba20a171',
  'd0fc520f-3fa2-5f08-be9b-05b7777e4542',
  '{"sub":"106476345377454385054","email":"warididada.standsyouth@gmail.com","email_verified":true,"full_name":"waridi dada","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocI_XNxC8tLMfHd5mbc4Ayu05Io5xEdcXGSufis3n6cuT8ixkA=s96-c"}'::jsonb,
  'google',
  '106476345377454385054',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: catherinegitau11@gmail.com (Firebase UID: uXPZB3rVhJaEqTMqje3SQ9SUqpy2 -> Supabase UUID: 74d79e69-c0ab-5c75-9da0-264a9b23c8ef)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '74d79e69-c0ab-5c75-9da0-264a9b23c8ef',
  'authenticated',
  'authenticated',
  'catherinegitau11@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"100023119151463075496","name":"Catherine Gitau","full_name":"Catherine Gitau","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocKkzQWsqbflhRMrgFlDoQ1Y9kjciGB7cFGof0NzhshDByaj3iyX=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocKkzQWsqbflhRMrgFlDoQ1Y9kjciGB7cFGof0NzhshDByaj3iyX=s96-c","email":"catherinegitau11@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '01754651-6753-401f-9021-5a856c5d6fd0',
  '74d79e69-c0ab-5c75-9da0-264a9b23c8ef',
  '{"sub":"100023119151463075496","email":"catherinegitau11@gmail.com","email_verified":true,"full_name":"Catherine Gitau","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocKkzQWsqbflhRMrgFlDoQ1Y9kjciGB7cFGof0NzhshDByaj3iyX=s96-c"}'::jsonb,
  'google',
  '100023119151463075496',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: gichaumburu@gmail.com (Firebase UID: v8M6WZQOA1aaxFP7DPRHna9NOOJ2 -> Supabase UUID: 0944fdbd-4794-5293-a133-925a2e541402)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '0944fdbd-4794-5293-a133-925a2e541402',
  'authenticated',
  'authenticated',
  'gichaumburu@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"100671424575136732940","name":"Alex Gichau","full_name":"Alex Gichau","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocJJzSL9W1tmaBd5jgZhZu_M5D3V2GxMP1-rRwAQxULNvyZX5fPe=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocJJzSL9W1tmaBd5jgZhZu_M5D3V2GxMP1-rRwAQxULNvyZX5fPe=s96-c","email":"gichaumburu@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  'a0cd295d-0189-42ad-815f-dc75c9cabd1a',
  '0944fdbd-4794-5293-a133-925a2e541402',
  '{"sub":"100671424575136732940","email":"gichaumburu@gmail.com","email_verified":true,"full_name":"Alex Gichau","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocJJzSL9W1tmaBd5jgZhZu_M5D3V2GxMP1-rRwAQxULNvyZX5fPe=s96-c"}'::jsonb,
  'google',
  '100671424575136732940',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

-- User: gathenya.watson@gmail.com (Firebase UID: zTsJF3T3HAOUhGmkABlqSVYAsxe2 -> Supabase UUID: b25777a2-4f7b-510c-ae5b-a08dfb098ea1)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  'b25777a2-4f7b-510c-ae5b-a08dfb098ea1',
  'authenticated',
  'authenticated',
  'gathenya.watson@gmail.com',
  '', -- OAuth users don't require encrypted password
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NULL,
  '{"provider":"google","providers":["google"]}'::jsonb,
  '{"iss":"https://accounts.google.com","sub":"117382791320774408326","name":"Watson Gathenya","full_name":"Watson Gathenya","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocICNfAbRXO4Kd4K9xwm_FTLKd3-hZ4fZ784jq4ryP00bBooKRz5_Q=s96-c","picture":"https://lh3.googleusercontent.com/a/ACg8ocICNfAbRXO4Kd4K9xwm_FTLKd3-hZ4fZ784jq4ryP00bBooKRz5_Q=s96-c","email":"gathenya.watson@gmail.com","email_verified":true}'::jsonb,
  FALSE,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  FALSE,
  NULL
) ON CONFLICT (id) DO UPDATE SET 
  raw_app_meta_data = EXCLUDED.raw_app_meta_data,
  raw_user_meta_data = EXCLUDED.raw_user_meta_data,
  email_confirmed_at = COALESCE(auth.users.email_confirmed_at, NOW());
INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  '1da2bb42-4f52-4721-a002-8ee2481f9e94',
  'b25777a2-4f7b-510c-ae5b-a08dfb098ea1',
  '{"sub":"117382791320774408326","email":"gathenya.watson@gmail.com","email_verified":true,"full_name":"Watson Gathenya","avatar_url":"https://lh3.googleusercontent.com/a/ACg8ocICNfAbRXO4Kd4K9xwm_FTLKd3-hZ4fZ784jq4ryP00bBooKRz5_Q=s96-c"}'::jsonb,
  'google',
  '117382791320774408326',
  NULL,
  NOW(),
  NOW()
) ON CONFLICT (provider, provider_id) DO UPDATE SET
  identity_data = EXCLUDED.identity_data,
  updated_at = NOW();

COMMIT;
